apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: document-service-staging-hpa
spec:
  maxReplicas: 6
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: document-service-staging
  metrics:
  - type: Resource
    resource:
      name: cpu
      target: 
        type: Utilization
        averageUtilization: 20
